CLASS zpru_todo_list DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS TODO.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zpru_todo_list IMPLEMENTATION.
  METHOD todo.
*21.12.2025
*1 ADD MESSAGED TO API
*2 IMPLEMENT METHOD ADD_QUERY_2_RUN IN API CLASS
*3 ADD ADDITIONAL FIELDS TO AGENT AND RUN TABLES
*4 EXPAND MESSAGES IN API WITH NEW FIELDS
*5 ADD VALIDATION INTO SERVICE CLASSES FOR AGENT AND RUN
*6 CHECK SAVE LOGIN IN SERVICE CLASSES FOR AGENT AND RUN
  ENDMETHOD.

ENDCLASS.
