CLASS zpru_cl_nested_http_schm_prvdr DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES ZPRU_IF_INPUT_SCHEMA_PROVIDER.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZPRU_CL_NESTED_HTTP_SCHM_PRVDR IMPLEMENTATION.


  METHOD zpru_if_input_schema_provider~get_input_schema.

  ENDMETHOD.
ENDCLASS.
