CLASS zpru_cl_nested_http_schm_prvdr DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES ZPRU_IF_INPUT_SCHEMA_PROVIDER.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZPRU_CL_NESTED_HTTP_SCHM_PRVDR IMPLEMENTATION.

  METHOD ZPRU_IF_INPUT_SCHEMA_PROVIDER~INPUT_JSON_SCHEMA.

  ENDMETHOD.

  METHOD ZPRU_IF_INPUT_SCHEMA_PROVIDER~INPUT_RTTS_SCHEMA.

  ENDMETHOD.

  METHOD ZPRU_IF_INPUT_SCHEMA_PROVIDER~OUTPUT_JSON_SCHEMA.

  ENDMETHOD.

  METHOD ZPRU_IF_INPUT_SCHEMA_PROVIDER~OUTPUT_RTTS_SCHEMA.

  ENDMETHOD.

ENDCLASS.
