CLASS zpru_cl_nested_short_memory DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zpru_cl_nested_short_memory IMPLEMENTATION.
ENDCLASS.
