CLASS zpru_cl_nested_long_memory DEFINITION INHERITING FROM zpru_cl_long_memory_base
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zpru_cl_nested_long_memory IMPLEMENTATION.

ENDCLASS.
